Customers
NSS-Therapeutic-Raccoons/BangazonAPI pull request #22
Opened 2018-10-30 20:52 UTC by jeremiah3643

## Link to Ticket
Closes #2 

## Description of Proposed Changes
- Created model for Customer
- Created mvc for Customer

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout customers
Add filler customers data into your SQL
Test POST, PUT, DELETE, and GET in POSTMAN
```
To further test, add q=(name you want to search) to url parameter to search by names of customers.
Add  _includes=(products or payments) to show what paymentTypes or products the customer has.

## Impacted Areas in Application

List general components of the application that this PR will affect:

* CustomersController and Customer(model)

## Mentions @username

@ricky-bruner 
@KHardt 
@askingalot 
@thatmikeparrish 

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

2018-10-30 21:02 UTC, thatmikeparrish approved these changes
Works for me

2018-10-31 00:41 UTC, askingalot requested changes
In addition to resolving my other comments, please include the README that we discussed.

2018-10-31 00:41 UTC, askingalot commented on BangazonAPI/Controllers/CustomersController.cs
> +        public async Task<IActionResult> Delete(int id)
There is no requirement to delete customers

2018-10-31 00:41 UTC, askingalot commented on BangazonAPI/Controllers/CustomersController.cs
> +            Console.WriteLine(sql);
Remove `Console.WriteLine()`

2018-10-31 00:41 UTC, askingalot commented on BangazonAPI/Controllers/CustomersController.cs
> +            Console.WriteLine(sql);
Remove `Console.WriteLine()`

2018-10-31 00:41 UTC, askingalot commented on BangazonAPI/Controllers/CustomersController.cs
> +            if (_include != null && _include.Contains("payments"))
What happens if I enter a URL such as http://localhost:5000/api/customers?_include=gimme_the_payments ?

2018-10-31 00:41 UTC, askingalot commented on BangazonAPI/BangazonAPI.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
What is this?

2018-10-31 00:41 UTC, askingalot commented on BangazonAPI/Controllers/CustomersController.cs
> +            else if (_include != null && _include.Contains("products"))
When `_include=products` is specified and a customer has not created any products, that customer is not being returned. I would expect to see the customer with an empty list of products.

2018-10-31 15:16 UTC, jeremiah3643 commented
Changes that @askingalot requested have been made. PR has been updated.

2018-10-31 15:56 UTC, askingalot approved these changes

2018-10-31 16:10 UTC, KHardt approved these changes
Looks good. Tested GET, PUT, POST, q/search, include products and include payments.

2018-10-31 16:10 UTC, merged